featured: false

title:
  fa: "AstroKit"
  en: "AstroKit"

description:
  fa: "یک کیت PHP برای توسعه قالب و ابزارهای وردپرسی مرتبط با طالع‌بینی، با ساختار مدیریتی، قالب پیش‌فرض و assetهای رابط کاربری."
  en: "A PHP toolkit for developing WordPress themes and astrology-related tools, featuring an admin structure, default theme, and reusable UI assets."

banner: "https://raw.githubusercontent.com/farid-teymouri/astrokit/main/assets/icon/astrokit.png"

preview: null

skills:
  - name: "WordPress"
    icon:
      light: "skill-icons:wordpress"
      dark: "skill-icons:wordpress"

  - name: "PHP"
    icon:
      light: "skill-icons:php-light"
      dark: "skill-icons:php-dark"

  - name: "JavaScript"
    icon:
      light: "skill-icons:javascript"
      dark: "skill-icons:javascript"

  - name: "GitHub"
    icon:
      light: "skill-icons:github-light"
      dark: "skill-icons:github-dark"
